# Generated by Django 6.0.2 on 2026-02-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='categoria',
            field=models.CharField(choices=[('General', 'General'), ('Anuncio', 'Anuncio'), ('Administrativo', 'Administrativo'), ('Deportes', 'Deportes'), ('Urgente', 'Urgente')], default='General', max_length=50),
        ),
        migrations.AddField(
            model_name='noticia',
            name='imagen_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
