# Generated by Django 6.0.2 on 2026-02-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_noticia_categoria_noticia_imagen_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='categoria',
            field=models.CharField(choices=[('General', 'General'), ('Anuncio', 'Anuncio'), ('Administrativo', 'Administrativo'), ('Deportes', 'Deportes'), ('Urgente', 'Urgent')], default='General', max_length=50),
        ),
    ]
