# Generated by Django 6.0.2 on 2026-02-16 20:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_noticia_categoria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inscripcion',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='imagen_url',
        ),
        migrations.AddField(
            model_name='archivoinstitucional',
            name='fecha_subida',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='noticias/'),
        ),
        migrations.AlterField(
            model_name='archivoinstitucional',
            name='archivo',
            field=models.FileField(upload_to='documentos_institucionales/'),
        ),
    ]
