# Generated by Django 6.0.2 on 2026-02-16 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_archivo_categoria_delete_archivoinstitucional_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archivo',
            old_name='nombre',
            new_name='titulo',
        ),
        migrations.AddField(
            model_name='archivo',
            name='categoria',
            field=models.CharField(choices=[('Planilla reingreso', 'Planilla reingreso'), ('Planilla nuevo ingreso', 'Planilla nuevo ingreso'), ('Otro', 'Otro')], default='Otro', max_length=50),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='archivo_pdf',
            field=models.FileField(upload_to='planillas/'),
        ),
    ]
